wandb_version: 1

ex1:
  desc: null
  value: 1
str_ex1:
  desc: null
  value: a string
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701463442.454767
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
